<a href="https://colab.research.google.com/github/CamFuenzalidaC/GuerrerosZ/blob/camilo_dev/Primera_evaluacion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np

Se carga el dataset desde GitHub utilizando la librería pandas. Esto permite acceder a los datos de forma remota sin necesidad de cargarlos manualmente en cada ejecución del notebook, facilitando el trabajo colaborativo y la reproducibilidad del análisis.

In [15]:
url = "https://raw.githubusercontent.com/CamFuenzalidaC/GuerrerosZ/ce340033c05f2b38c72ffdbfad7d39d310892e07/Spotify_Music.csv"
df = pd.read_csv(url)

Se visualizan las primeras filas del dataset para comprender su estructura, identificar los nombres de las columnas y obtener una primera impresión de los datos disponibles.

In [16]:
df.head(5)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

Se Visualizan las ultimas 5 filas del Daaa set

In [17]:
df.tail(10)

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
113990,113990,2A4dSiJmbviL56CBupkh6C,Lucas Cervetti,Frecuencias Álmicas en 432hz (Solo Piano),Frecuencia Álmica XI - Solo Piano,22,369049,False,0.579,0.245,...,-16.357,1,0.0384,0.97000,0.924000,0.1010,0.3020,112.011,3,world-music
113991,113991,0CE0Y6GM75cbrqao8EOAlW,Chris Tomlin,The Ultimate Playlist,At The Cross (Love Ran Red),32,250629,False,0.387,0.531,...,-4.788,1,0.0290,0.00305,0.000000,0.2010,0.1530,146.003,4,world-music
113992,113992,3FjOBB4EyIXHYUtSgrIdY9,Jesus Culture,Revelation Songs,Your Love Never Fails,38,312566,False,0.475,0.860,...,-4.722,1,0.0421,0.00650,0.000002,0.2460,0.4270,113.949,4,world-music
113993,113993,4OkMK49i3NApR1KsAIsTf6,Chris Tomlin,See The Morning (Special Edition),How Can I Keep From Singing,39,256026,False,0.505,0.687,...,-4.375,1,0.0287,0.08410,0.000000,0.1880,0.3820,104.083,3,world-music
113994,113994,4WbOUe6T0sozC7z5ZJgiAA,Lucas Cervetti,Frecuencias Álmicas en 432hz,"Frecuencia Álmica, Pt. 4",22,305454,False,0.331,0.171,...,-15.668,1,0.0350,0.92000,0.022900,0.0679,0.3270,132.147,3,world-music
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.235,...,-16.393,1,0.0422,0.64000,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.117,...,-18.318,0,0.0401,0.99400,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.329,...,-10.895,0,0.0420,0.86700,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.506,...,-10.889,1,0.0297,0.38100,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.487,...,-10.204,0,0.0725,0.68100,0.000000,0.0893,0.7080,79.198,4,world-music

Se analiza la cantidad de filas y columnas del dataset con el fin de conocer su tamaño. Esto permite verificar si el conjunto de datos es lo suficientemente amplio para realizar análisis y կիրառar modelos de machine learning en etapas posteriores.

In [18]:
df.shape # contas filas y columnas

(114000, 21)

Se identifican los valores nulos en cada columna para evaluar la calidad de los datos. La presencia de valores faltantes puede afectar el análisis y los modelos, por lo que es importante detectarlos antes de continuar.

In [19]:
df.isna().sum() # cuenta los nulos totales

Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

Detectamos las filas con valores nulos dentro del Data Set

In [20]:
df[df.isnull().any(axis=1)] #detectar la fila nula

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
65900,65900,1kR4gIb7nGxHPI3D2ifs59,NaN,NaN,NaN,0,0,False,0.501,0.583,...,-9.46,0,0.0605,0.69,0.00396,0.0747,0.734,138.391,4,k-pop

Se eliminan las filas que contienen valores nulos con el objetivo de trabajar con un dataset limpio. Esto evita errores en los análisis posteriores y mejora la calidad de los resultados.

Como es una sola fila la procedemos a eliminar ya que no afecta

In [21]:
df=df.dropna()#elimina la fila  nula

Ya no quedan nulos y podemos empezar a analizar los datos

In [22]:
df.isna().sum() # muestra que ya no esta la fila del nula

Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64




---


---









###                                                         ANALIZIS DE DATOS








---


---